Added Ukrainian translation
usetrmnl/localizations pull request #4
Opened 2024-07-24 21:23 UTC by veikus

2024-07-24 21:27 UTC, veikus commented
It would be great if someone could review this as well.

2024-07-25 03:44 UTC, ryanckulp commented
thank you @veikus ! we have 2 team members in Kyiv, will ask them to review so we can merge.

2024-07-25 08:32 UTC, yankobogdan requested changes

2024-07-25 08:32 UTC, yankobogdan commented on locales/uk-UA.yml
> +  keep_me_signed_in: Залишатися увійденим # TODO: Find a better translation
Залишатись у системі

2024-07-25 08:32 UTC, yankobogdan commented on locales/uk-UA.yml
> +  forgot_password_title: Почнемо з початку # heading on /password/new # TODO: Maybe someone find a better translation. "Гайда знову"?
I like "Гайда знову" or "Отакої...Гайда знову"

2024-07-25 08:32 UTC, yankobogdan commented on locales/uk-UA.yml
> +      time_zone_hint: Визначає частоту оновлення та тривалість режиму сну пристрою.
Визначає частоту оновлення та розклад сну пристрою.

2024-07-25 08:32 UTC, yankobogdan commented on locales/uk-UA.yml
> +      mirror_device_hint: Надайте ідентифікатор спільного пристрою, щоб дзеркалити його плейлист. Ваш плейлист також буде відображатися. # TODO: Check the translation of "shareable"
Надайте ID пристрою з увімкненим спільним доступом, щоб дзеркалити його плейлист. Ваш плейлист також буде відображатися.

2024-07-25 08:32 UTC, yankobogdan commented on locales/uk-UA.yml
> +      visibility: Видимість # TODO: "Спільний доступ"?
Спільний доступ

2024-07-25 08:32 UTC, yankobogdan commented on locales/uk-UA.yml
> +      error_not_shared: Вказаний ідентифікатор пристрою не доступний для спільного використання
Вказаний ідентифікатор пристрою не доступний для спільного доступу

2024-07-25 08:34 UTC, yankobogdan commented
@veikus Дякую за твій вклад!
Thank you for your contribution!

2024-07-25 08:44 UTC, veikus commented
@yankobogdan Thank you for the editing!

2024-07-25 15:17 UTC, merged